### ISSUE TITLE
add "source: auto" option?

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/differ#2]
The PF service has a "source:auto" option which lets you compare a URL against an html blob (they pushed that quite late and  I never pushed the doc change to the repo, so that's my screwup). This is particularly useful for testing b/c we still don't have a second set of packages from pagefreezer, so in order to run tests we need to diff against live URL's.  

How hard would this be to implement? I don't suppose there's any chance of getting it done before we break for lunch her in SF (~3pm EST)?

**Comment by WestleyArgentum** [comment]
cool, done in c3298e9c036fb7a51e9865109b3b4be05e230fa3

**Comment by titaniumbones** [comment]
unreal, thx
